config/routes.rb
Rails.application.routes.draw do
  get 'searches/search'
  get 'relationships/followings'
  get 'relationships/followers'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
  root :to =>"homes#top"
  get "home/about"=>"homes#about"
  
  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  resources :users, only: [:index,:show,:edit,:update] do
    resource :relationships, only:[:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end
  
  get "search" => "searches#search"
  
  end
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def search
    @range = params[:range]
    @word = params[:word]
    if @range == "User"
      @users = User.looks(params[:search], params[:word])
    else
      @books = Book.looks(params[:search], params[:word])
    end
  end
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/searches/_search.html.erb
<% if user_signed_in? %>
   <div class="search_form">
     <%= form_with url: search_path, local: true, method: :get do |f| %>
      <%= f.text_field :word %>
      <%= f.select :range, options_for_select([['User'], ['Book']]) %>
      <%= f.select :search, options_for_select([["完全一致","perfect_match"], ["前方一致","forward_match"], ["後方一致","backward_match"], ["部分一致","partial_match"]]) %>
      <%= f.submit "検索", class: "btn btn-secondary btn-sm" %>
     <% end %>
   </div>
<% end %>

app/views/searches/search.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-11'>
      <% if @range == "User" %>
       <h2>Users search for "<%= @word %>"</h2>
       <table class="table table-hover table-inverse">
          <tbody>
            <% @users.each do |user| %>
             <tr>
              <th></th>
              <th>Name</th>
              <th>Introduction</th>
              <th></th>
             </tr>
             <tr>
              <td><%= image_tag user.get_profile_image(50, 50) %></td>
              <td><%= user.name %></td>
              <td><%= user.introduction %></td>
              <td><%= link_to "Show", user %></td>
              </tr>
            <% end %>
          </tbody>
       </table>
      <% else %>
       <h2>Books search for <%= @word %></h2>
       <table class="table table-hover table-inverse">
          <tbody>
            <% @books.each do |book| %>
             <tr>
              <th></th>
              <th>Title</th>
              <th>Opinions</th>
              <th></th>
             </tr>
             <tr>
              <td><%= image_tag book.user.get_profile_image(50, 50) %></td>
              <td><%= link_to book_path(book.user) do %>
                   <%= book.title %>
                  <% end %></td>
              <td><%= book.body %></td>
              </tr>
            <% end %>
          </tbody>
       </table>
      <% end %>
    </div>
  </div>
</div>